# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SourceCode' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'MaterialTextField'
pod 'MaterialComponents/TextControls+OutlinedTextFields'
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'IQKeyboardManagerSwift'
pod 'NVActivityIndicatorView'
pod 'JWTDecode', '~> 2.6'
pod 'GrowingTextView', '0.7.2'


  # Pods for SourceCode

  target 'SourceCodeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SourceCodeUITests' do
    # Pods for testing
  end

end
