# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SourceCode' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'MaterialTextField'

  # Pods for SourceCode

  target 'SourceCodeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SourceCodeUITests' do
    # Pods for testing
  end

end
